name: cos
description: "Car on Sale Flutter Challange"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  async: ^2.13.0
  collection: ^1.19.1
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  gap: ^3.0.1
  get_it: ^8.0.3
  go_router: ^15.2.0
  google_fonts: ^6.2.1
  http: ^1.4.0
  intersperse: ^2.0.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logging: ^1.3.0
  meta: ^1.16.0
  retrofit: ^4.4.2
  shared_preferences: ^2.5.3
  stack_trace: ^1.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/toyota_gt_86.png
    - assets/images/car_search.png
    - assets/images/car_broken.png
